const ACH_DATA = [
    {
        id: "first_bingo",
        name: "First Steps",
        desc: "Get your first Bingo!",
        icon: "🗺️",
        type: "milestone",
    },
    {
        id: "speed_demon",
        name: "Speed Demon",
        desc: "Bingo in under 5 minutes",
        icon: "⚡",
        type: "sprint",
    },
    {
        id: "gardener",
        name: "LAWNMOWER!",
        desc: "Find 5 Lawnmowers",
        icon: "🌱",
        type: "collection",
        goal: 5,
        goalType: "item",
        itemKey: "Lawnmower",
    },
    {
        id: "caravan_hunter",
        name: "a CAraVAAAN!?",
        desc: "Find 5 Caravans",
        icon: "🚐",
        type: "collection",
        goal: 5,
        goalType: "item",
        itemKey: "Caravan",
    },
    {
        id: "master_hunter",
        name: "Completionist",
        desc: "Find every item at least 5 times",
        icon: "👑",
        type: "milestone",
    },
    {
        id: "world_traveler",
        name: "World Traveler",
        desc: "Play a game in 5 different countries",
        icon: "✈️",
        type: "exploration",
    },
    {
        id: "streak_3",
        name: "Streak Hunter",
        desc: "Play for 3 consecutive days",
        icon: "🔥",
        type: "milestone",
    },
    {
        id: "streak_5",
        name: "High Five",
        desc: "Keep the momentum for 5 consecutive days",
        icon: "✋",
        type: "milestone",
    },
    {
        id: "streak_7",
        name: "Weekly Wanderer",
        desc: "A full week of global exploration",
        icon: "📅",
        type: "milestone",
    },
    {
        id: "streak_10",
        name: "Double Digits",
        desc: "10 days of non-stop Bingo",
        icon: "🔟",
        type: "milestone",
    },
    {
        id: "streak_20",
        name: "Routine Rover",
        desc: "20 consecutive days. It's a habit now!",
        icon: "👟",
        type: "milestone",
    },
    {
        id: "streak_30",
        name: "Full Moon",
        desc: "One entire month of daily Street View discovery",
        icon: "🌕",
        type: "milestone",
    },
    {
        id: "streak_50",
        name: "The Half Century",
        desc: "50 days of scouting the globe",
        icon: "🏆",
        type: "milestone",
    },
    {
        id: "streak_75",
        name: "Diamond Jubilee",
        desc: "75 consecutive days of exploration",
        icon: "💎",
        type: "milestone",
    },
    {
        id: "streak_100",
        name: "Centurion",
        desc: "The ultimate milestone: 100 consecutive days",
        icon: "👑",
        type: "milestone",
    },
    {
        id: "marathoner",
        name: "Marathoner",
        desc: "Accumulate 1 hour of total playtime",
        icon: "🏃",
        type: "milestone",
        goal: 3600000,
        goalType: "stat",
        statKey: "totalPlaytime",
    },
    {
        id: "london_calling",
        name: "London Calling",
        desc: "Find an item while exploring London",
        icon: "🎡",
        type: "exploration",
    },
    {
        id: "the_patriot",
        name: "The Patriot",
        desc: "Find a flag while exploring the United States",
        icon: "🏳️",
        type: "exploration",
    },
    {
        id: "quick_start",
        name: "Off to the Races",
        desc: "Find your first item within 5 seconds of starting",
        icon: "🏁",
        type: "sprint",
    },
    {
        id: "animal_lover",
        name: "Animal Lover",
        desc: "Find a total of 10 Dogs or Cats",
        icon: "🐈",
        type: "collection",
        goal: 10,
        goalType: "item",
        itemKey: "Dog or Cat",
    },
    {
        id: "double_tap",
        name: "Double Tap",
        desc: "Capture 2 items within 2 seconds of each other",
        icon: "🎯",
        type: "sprint",
    },
    {
        id: "the_commuter",
        name: "The Commuter",
        desc: "Collect 10 Bicycles, 10 Motorbikes, and 10 Caravans",
        icon: "🚲",
        type: "collection",
    },
    {
        id: "logistics_expert",
        name: "Logistics Expert",
        desc: "Collect 10 Work Vans, 10 Trailers, and 10 Ladders",
        icon: "📦",
        type: "collection",
    },
    {
        id: "high_vis_hero",
        name: "High-Vis Hero",
        desc: "Find a total of 20 People wearing Hi-Vis",
        icon: "👷",
        type: "collection",
        goal: 20,
        goalType: "item",
        itemKey: "Person wearing Hi-Vis",
    },
    {
        id: "island_hopper",
        name: "Island Hopper",
        desc: "Explore both the United Kingdom and Australia",
        icon: "🏝️",
        type: "exploration",
        goal: 2,
        goalType: "custom",
    },
    {
        id: "scandinavian_scout",
        name: "Scandinavian Scout",
        desc: "Find an item in Norway, Sweden, and Denmark",
        icon: "❄️",
        type: "exploration",
        goal: 3,
        goalType: "custom",
    },
    {
        id: "elite_explorer",
        name: "Elite Explorer",
        desc: "Achieve a full Bingo at precisely 13:37",
        icon: "🎮",
        type: "tactical",
        hidden: true,
    },
];
